### json-server reference: https://www.npmjs.com/package/json-server

### /posts - plural routes
### GET get all posts
GET http://localhost:3001/api/posts HTTP/1.1
Content-Type: application/json

### GET get one post with id 2
GET http://localhost:3001/api/posts/2 HTTP/1.1
Content-Type: application/json

### /comments
### GET get all comments
GET http://localhost:3001/api/comments HTTP/1.1
Content-Type: application/json

### profile - singular route
### GET get a profile
GET http://localhost:3001/api/profile HTTP/1.1
Content-Type: application/json

### GET a comment
GET http://localhost:3001/api/posts/getComments?postId=1 HTTP/1.1
Content-Type: application/json
